name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive          

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: latest

      - name: List files
        run: ls -al ../
        
      - name: Build local site
        run: hugo --minify --gc --destination ./public --source ./ --themesDir ./themes --baseURL https://curiouscassie.github.io/
        
      - name: List files
        run: ls -al . && ls -al ../ && pwd

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
